### ISSUE TITLE
Select og:image for each page

### ISSUE THREAD

**Issue by davidluhr** [other-pieces/otherpieces.com#103]

**Comment by saramccaskey** [comment]
Homepage: https://drive.google.com/drive/u/0/folders/1fefWYbhATDRRqSWKw8WlYjBDle5ZlKtS
Style: https://drive.google.com/drive/u/0/folders/1fefWYbhATDRRqSWKw8WlYjBDle5ZlKtS
Lifestyle: https://drive.google.com/drive/u/0/folders/1fefWYbhATDRRqSWKw8WlYjBDle5ZlKtS
Travel: https://drive.google.com/drive/u/0/folders/1fefWYbhATDRRqSWKw8WlYjBDle5ZlKtS
About: https://drive.google.com/drive/u/0/folders/1mnRGM_6JSMhJpxmLc9wA3T4_s0GJqaUa
