### ISSUE TITLE
Create About Us Content

### ISSUE THREAD

**Issue by saramccaskey** [other-pieces/otherpieces.com#19]

**Comment by saramccaskey** [comment]
https://docs.google.com/document/d/1KpU9oZ9sIiN2K7JbwUbUy-m6bemtVaMSab3MWD9FRQ8/edit

**Comment by saramccaskey** [comment]
![img_5456 1](https://user-images.githubusercontent.com/28202858/44434986-31c6dc80-a56b-11e8-92b6-2ae2c80254a0.JPG)
![img_5475 1](https://user-images.githubusercontent.com/28202858/44434988-34293680-a56b-11e8-8e16-8eebee4eac76.JPG)

Photos for About Us page

**Comment by jacquedobbins** [comment]
- [ ] write content

- [ ] select photos

- [ ] add photos

- [ ] edit content
