### ISSUE TITLE
Build about page

### ISSUE THREAD

**Issue by davidluhr** [other-pieces/otherpieces.com#9]

**Comment by saramccaskey** [comment]
Final Copy: https://docs.google.com/document/d/1KpU9oZ9sIiN2K7JbwUbUy-m6bemtVaMSab3MWD9FRQ8/edit

**Comment by saramccaskey** [comment]
Final Copy and Photos: https://drive.google.com/drive/u/0/folders/1mnRGM_6JSMhJpxmLc9wA3T4_s0GJqaUa
