### ISSUE TITLE
Add final images to site

### ISSUE THREAD

**Issue by davidluhr** [other-pieces/otherpieces.com#91]

**Comment by saramccaskey** [comment]
About Us Photos
https://drive.google.com/open?id=1aS9sSKVcN7jOlk17L4aJNO6FkzQDZ1QC
https://drive.google.com/open?id=1GZ-a9Z0U7OxOoIIBUoBPyGw_Ejjc6KnX

**Comment by saramccaskey** [comment]
Style Photo:
https://drive.google.com/open?id=130hcsx8VfM4UD7G8s8ESNkDwbOpGh1Hj

Lifestyle Photo:
https://drive.google.com/open?id=1gq5ThVN0c9vPWlyjak6_g-CqLhW0wnC9

Travel Photo:
https://drive.google.com/open?id=1PdJYQM-1OTA8QlvJQtbdluxZtdC0n7E1
